### ISSUE TITLE
Convert it to a docs package

### ISSUE THREAD

**Issue by idkq** [lulupointu/vrouter_website#2]
This is beautiful! well done - it would be great to convert it to a package so others can build 'tutorial/docs' like pages

**Comment by lulupointu** [comment]
Thanks 😊

However I don't really understand what you mean be converting it to a package. You mean that other people would use this as a template? If this is the case I don't think I would not have the time to adapt and maintain it. This is open source though so you can make it if you want 😁

**Comment by idkq** [comment]
Sure no problem, it was just an idea, something like this https://github.com/readthedocs/readthedocs.org

**Comment by lulupointu** [comment]
If flutter web develops to be more compatible with document centric needs I might reconcider but not right now 😉
