### ISSUE TITLE
Add Hover effects on links

### ISSUE THREAD

**Issue by evandrmb** [lulupointu/vrouter_website#4]
![image](https://user-images.githubusercontent.com/47798920/119228538-d0e8dc00-bae9-11eb-87e3-5f261b72f328.png)

Currently, links like the above don't have a hover effect when moving the mouse above it which feels weird for the web. I believe it could be fixed by adding `mouseCursor: MaterialStateMouseCursor.clickable,` to the TextSpan

Would you mind if I did a PR to fix this?

**Comment by lulupointu** [comment]
Please go ahead!

**Comment by lulupointu** [comment]
Closing since it's done thanks to you 😊
