### ISSUE TITLE
In Guides, the left nav does not scroll to current Navigation path if your screen is to small.

### ISSUE THREAD

**Issue by gedw99** [lulupointu/vrouter_website#7]
VRouter is really easy to work with. thanks for making this project and the high quality docs.

One thing that is bugging me is the Navigation in the guide. 

If you click on https://vrouter.dev/guide/Advanced/Custom%20Pages, the left nav pane does not scroll down to the "Guide" text.

Same goes for if you then click on "History State" in the left nav.

this bug of course depends on the size / DPi of your screen.

https://user-images.githubusercontent.com/53147028/123487813-f6986200-d60e-11eb-9350-ffa16f69f6bd.mov

**Comment by lulupointu** [comment]
Fixed, along with other nice features like:
- The left navigation bar is no longer rebuild
- It keeps it's scroll position
- It adapts if the browser back/forward button is pressed to always have the current section visible
