### ISSUE TITLE
UX: Add the ability to copy the URL from a Heading in the main Pane. 

### ISSUE THREAD

**Issue by gedw99** [lulupointu/vrouter_website#8]
In many documentation sites, you often have a copy link next to a Heading, so that the user can easily copy the link and reuse it somewhere else.

A the moment, the user has to go up to the Browser URL to copy it, if using a browser.
Even worse however, If using it in an App, there is no way for them to copy the URL at all.

So, it would improve the docs UX if a Copy Link was present next to each heading.

Here is an example: https://www.docsy.dev/docs/#what-is-docsy

https://user-images.githubusercontent.com/53147028/123488499-5a6f5a80-d610-11eb-9c87-1f094f77f5a1.mov

**Comment by lulupointu** [comment]
Done.

If I wanted to release an app version and deep linking to work this would require a bit more work though following https://flutter.dev/docs/development/ui/navigation/deep-linking

Anyway, since we are only interested in the web version this is done :wink:
